import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Register | Weycler",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <main className="bg-[#F1F1F8]">{children}</main>
      </body>
    </html>
  );
}
